### ISSUE TITLE
Autoupdater

### ISSUE THREAD

**Issue by ghost** [RobinPerris/Crystalshire#3]
Hello Robin!

i was wondering how to setup the Autoupdater. I just created the folder on the webserver. But what i have to do with the crc.php file or how i create a update file?

Thank you for answer and help!

**Comment by RobinPerris** [comment]
crc.php was something I created to easily generate the list of file hashes for the updater. If you run that script within a web server folder where your game files are, it'll loop through and generate a list of all their crc32 checksums in a .txt file.

If I remember correctly you have to point the updater to the text file that is generated by that script to have it compare the user's local data file versions against those on the server.

A bit of trial and error should help you figure it out once you have the script working. Good luck.

**Comment by ghost** [comment]
I just got it working, my problem was that the crc.php did not get executed and just showed a blank space in browser, then i realized that you are using short-tags <? in the script and not every server does execute it so i had to edit it to <?php instead. Anyway thank you a lot for your fast answer. I really appreciate it!
